### PR TITLE
[15.0][3900][MIG] product_barcode_compute: Migration to 15.0

### PR DESCRIPTION
**Pull request by AungKoKoLin1997**
[3900](https://www.quartile.co/web#cids=3&menu_id=505&action=1457&model=project.task&view_type=form&id=3900)

### CODE REVIEW

**Comment by AungKoKoLin1997** [comment]
Tests are failed because same default code is set up for different products in https://github.com/qrtl/rmm-custom/blob/26596adb0f5de139d687bc05b5d59c1a90d12e31/product_yahoo_auction_sst/data/delivery_carrier_data.xml#L4-L32. 

@kanda999  Is there any reason for setting up same default code for different products? If not, we may adjust this.

**Comment by kanda999** [comment]
@AungKoKoLin1997 I checked and `default_code` does not mean the same thing. We should use a different one.

**Comment by AungKoKoLin1997** [comment]
> I checked and `default_code` does not mean the same thing. We should use a different one.

@kanda999 Can you please help me to change about it because I don't know what `default_code` value should be changed? After that, I will rebase current PR to fix tests CI failed.

**Comment by kanda999** [comment]
@AungKoKoLin1997 Fixed the default_code . Don't forget to pre-commit again after rebasing.

**Review by kanda999 — APPROVED** [review]
Functional and Code review

**Pull request merged**
