### PR TITLE
[4561][IMP] product_auction

### PR DESCRIPTION
**Pull request by AungKoKoLin1997**
[4561](https://www.quartile.co/web#id=4561&menu_id=505&cids=3&action=1457&model=project.task&view_type=form)

### CODE REVIEW

**Review by kanda999 — APPROVED** [review]
Functional and code review

**Comment by AungKoKoLin1997** [comment]
@kanda999  I don't remember there is task for this PR. If not, I will create the new one.

**Comment by kanda999** [comment]
@AungKoKoLin1997 
Please create new ticket.

**Comment by AungKoKoLin1997** [comment]
I think we should separate PR for each module. I will follow up on this.

**Review by yostashiro — APPROVED** [review]

**Pull request merged**
