### PR TITLE
[5044][IMP] account_commission_sales_fee: Include zero-price items in commission calculation

### PR DESCRIPTION
**Pull request by nobuQuartile**
[5044](https://www.quartile.co/web?db=qrtl&token=z9OpY14OSBGGYn2qv0Ha#id=5044&cids=3&menu_id=505&action=1457&model=project.task&view_type=form)
- Adjusted the logic to count records with `line.settled_amount >= 0.0` for commissionable items.

### CODE REVIEW

**Review by yostashiro — COMMENTED** [review]
@nobuQuartile Can you please update the commit message to mention the why, not the what?

**Comment by nobuQuartile** [comment]
@yostashiro I updated the commit message.

**Review by yostashiro — APPROVED** [review]
nitpick: Regarding the commit message, strictly speaking, it's a 'sales fee' rather than a 'commission fee' in our terms.

**Comment by nobuQuartile** [comment]
I update the commit message.

**Review by kanda999 — APPROVED** [review]
Functional and code review.

**Pull request merged**
