### PR TITLE
[UPD] Dotfiles from repo template

### PR DESCRIPTION
**Pull request by rinaldifirdaus**
General Maintenance

### CODE REVIEW

**Comment by kanda999** [comment]
@rinaldifirdaus 
For rmm-custom dotfile, please see https://github.com/qrtl/rmm-custom/pull/56

**Comment by rinaldifirdaus** [comment]
> @rinaldifirdaus For rmm-custom dotfile, please see #56

Im sorry i didn't aware of the updates. Hence, i will close this PR. Thank you

**Comment by kanda999** [comment]
@rinaldifirdaus 
> Im sorry i didn't aware of the updates. Hence, i will close this PR. Thank you

This PR was causing conflicts. Did you aware that?  Commit history is strange too.
If you've awared, please try to correct it next time.  Of course, you can ask me :)

**Comment by rinaldifirdaus** [comment]
> @rinaldifirdaus
> 
> > Im sorry i didn't aware of the updates. Hence, i will close this PR. Thank you
> 
> This PR was causing conflicts. Did you aware that? Commit history is strange too. If you've awared, please try to correct it next time. Of course, you can ask me :)

Oh yeah, the commit history was so strange, it includes my previous commit..... Im sorry for messing things up >.<
Is that happens because of there was pending commits that I didn't push from my my local, and eventually it is pushed with the recent commit?

**Comment by kanda999** [comment]
@rinaldifirdaus 
I don't know the details, but your local repository is not up to date so get those commit history.
Please `git pull ` before you create release branch.

**Comment by rinaldifirdaus** [comment]
>I don't know the details, but your local repository is not up to date so get those commit history. Please `git pull ` before you create release branch.

I see. I will pay attention on this in the future regarding this.. Thank you so much @kanda999 san for your review and input!

**Pull request closed without merging**
