### PR TITLE
[3829][15.0] [UPD] dotfiles

### PR DESCRIPTION
**Pull request by liuhehe1995**
[3829](https://www.quartile.co/web#id=3829&menu_id=505&cids=3&action=1457&model=project.task&view_type=form)

### CODE REVIEW

**Comment by AungKoKoLin1997** [comment]
@liuhehe1995 
I add new commit to revert pylint version to match with current .pylintrc format. You can see the story why we use this version in here https://github.com/OCA/odoo-pre-commit-hooks/issues/88.

**Comment by yostashiro** [comment]
> I add new commit to revert pylint version to match with current .pylintrc format.

@AungKoKoLin1997 Doesn't copier update automatically update the pylint-odoo version?

**Comment by AungKoKoLin1997** [comment]
> Doesn't copier update automatically update the pylint-odoo version?

Yes. oca-addon-repo-template doesn't use the latest the pylint version and I don't know the reason(may be the stable version). With default version, there is issue for oca-hook:disable. We need to use this disable because we have some replacement for fields in our modules.

**Comment by yostashiro** [comment]
@AungKoKoLin1997 I wonder if there is a way to remember this local adjustment. Can you also please double check that there was no other way than using `replace` where `<!-- oca-hooks:disable=xml-view-dangerous-replace-low-priority -->` was used? The best is to avoid the use of `replace` instead of subdueing the warning.

**Comment by AungKoKoLin1997** [comment]
I added a new commit to use OCA standard pylint version and remove oca-hook:disable with adding priority to views that have replacement fields. I think this is the best way not to complex the process.

I think it is difficult to avoid using replace in `auction_seller_invoice`. So, I will keep it at the moment.

**Review by AungKoKoLin1997 — APPROVED** [review]

**Review by yostashiro — APPROVED** [review]
Thanks Lin. LTGM.

@kanda999 Please merge this upon confirming that this update does not break `auction_seller_invoice`.

**Review by kanda999 — APPROVED** [review]
There was no problem with auction_seller_invoice module.

**Pull request merged**
