### PR TITLE
[15.0][3908][MIG] product_group_product_manager: Migration to 15.0

### PR DESCRIPTION
**Pull request by AungKoKoLin1997**
[3908](https://www.quartile.co/web#cids=3&menu_id=505&action=1457&model=project.task&view_type=form&id=3908)

### CODE REVIEW

**Comment by yostashiro** [comment]
For some reason the translation is missing. Thought @kanda999 had done it but we may have just missed it.

**Comment by yostashiro** [comment]
@AungKoKoLin1997 This PR seems to include unrelated files. Please check.

**Comment by AungKoKoLin1997** [comment]
> This PR seems to include unrelated files. Please check.

Yes. It comes from pre-commit. I rebase PR.

**Review by yostashiro — APPROVED** [review]

**Review by kanda999 — APPROVED** [review]
Functional test

**Pull request merged**
